### ISSUE TITLE
v1.0 Tracking Issue

### ISSUE THREAD

**Issue by vaaaaanquish** [m3dev/gokart#184]
[TODO]

- [x] Add Logo #198 
- [x] compress tree info #192 
- [x] Add running gokart task on interpreter #183 
- [x] Add examples #185
- [x] Fix Documents #185
- [x] Fix GCSClient bug https://github.com/m3dev/gokart/issues/187
- [x] specific load https://github.com/m3dev/gokart/issues/189

**Comment by vaaaaanquish** [comment]
Add running gokart task on interpreter: https://github.com/m3dev/gokart/pull/183

**Comment by vaaaaanquish** [comment]
Fix document: #185

**Comment by vaaaaanquish** [comment]
branch: https://github.com/m3dev/gokart/tree/1.0.0

**Comment by vaaaaanquish** [comment]
merged 🎉  #185

**Comment by vaaaaanquish** [comment]
merged 🎉 #189

**Comment by hirosassa** [comment]
merged 🎉 https://github.com/m3dev/gokart/pull/191

**Comment by hirosassa** [comment]
merged 🎉 https://github.com/m3dev/gokart/pull/183

**Comment by Hi-king** [comment]
Merged #192 

So, all we need is just a logo!!!!!!!!!!

**Comment by hirosassa** [comment]
Yeah!!

**Comment by vaaaaanquish** [comment]
Added logo #198 🎉

**Comment by Hi-king** [comment]
So... Are we ready now? @hirosassa @vaaaaanquish

**Comment by vaaaaanquish** [comment]
Yeah! Go!Go!

**Comment by vaaaaanquish** [comment]
Merged. Please wait for release.

**Comment by hirosassa** [comment]
@vaaaaanquish @Hi-king @saya-kawakami @mski-iksm Thanks for your great contributions!
